[tool.black]
line-length = 120

[tool.isort]
line_length = 120

[tool.pytest.ini_options]
minversion = "7.3.1"
addopts = "-vv"
python_files = ["test_*.py"]
python_classes = ["Test"]
python_functions = ["test"]
testpaths = ["tests"]